# Generated by Django 3.2.5 on 2021-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
